Update webpack.yml

diff --git a/.github/workflows/webpack.yml b/.github/workflows/webpack.yml
--- a/.github/workflows/webpack.yml
+++ b/.github/workflows/webpack.yml
@@ -26,7 +26,8 @@ jobs:
     - name: Build
       run: |
         npm install
-        npx webpack
+        npx webpack --verbose || echo "Build failed" && exit 1
+        
     - name: Clone the deployment repository
       run: |
         git clone https://github.com/tedfak/svgsmsc-site.git svgsmsc-site
